"use client";
import { useEffect, useMemo, useState } from "react";
import { createGradeSixCylinderSet, normalizeCylinderAnswer } from "../../../lib/grade-six-cylinder";
import type { CylinderProblem } from "../../../lib/grade-six-cylinder";
type PrintMode = "worksheet" | "answers" | "both"; type Field = "surfaceArea" | "volume";
export default function GradeSixCylinderPage() {
  const [seed, setSeed] = useState(20260723); const [answers, setAnswers] = useState<Record<string, Partial<Record<Field, string>>>>({}); const [results, setResults] = useState<Record<string, boolean>>({}); const [scale, setScale] = useState(.6); const [printOpen, setPrintOpen] = useState(false); const problems = useMemo(() => createGradeSixCylinderSet(seed), [seed]); const correct = Object.values(results).filter(Boolean).length;
  useEffect(() => { const fit = () => setScale(Math.min((innerWidth - 32) / 794, 1)); fit(); addEventListener("resize", fit); return () => removeEventListener("resize", fit); }, []);
  const update = (id: string, field: Field, value: string) => { setAnswers((now) => ({ ...now, [id]: { ...now[id], [field]: value.replace(/[^0-9.]/g, "").slice(0, 9) } })); setResults((now) => { const next = { ...now }; delete next[`${id}-${field}`]; return next; }); };
  const reset = () => { setAnswers({}); setResults({}); }; const fresh = () => { if (Object.values(answers).some((value) => Object.values(value).some(Boolean)) && !confirm("답이 사라집니다. 새 문제를 만들까요?")) return; setSeed((Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0); reset(); };
  const check = () => setResults(Object.fromEntries(
    problems.flatMap((p) => (["surfaceArea", "volume"] as const).map((field) => [
      `${p.id}-${field}`,
      normalizeCylinderAnswer(answers[p.id]?.[field] ?? "") === p[field],
    ])),
  ));
  const print = (mode: PrintMode) => { setPrintOpen(false); document.documentElement.dataset.printMode = mode; addEventListener("afterprint", () => delete document.documentElement.dataset.printMode, { once: true }); requestAnimationFrame(() => window.print()); };
  const answer = (p: CylinderProblem, field: Field, key: boolean) => { const id = `${p.id}-${field}`, okay = results[id] === true, unit = `${p.unit}${field === "surfaceArea" ? "²" : "³"}`; return <div className={`cylinder-answer${id in results ? okay ? " is-correct" : " is-wrong" : ""}`}><span>{field === "surfaceArea" ? "겉넓이" : "부피"}</span><strong>=</strong>{key ? <em>{p[field]}</em> : <input type="text" inputMode="decimal" value={answers[p.id]?.[field] ?? ""} onChange={(event) => update(p.id, field, event.target.value)} aria-label={`${p.id} ${field === "surfaceArea" ? "겉넓이" : "부피"}`} />}<small>{unit}</small>{!key && id in results && <b className={okay ? "correct" : "wrong"}>{okay ? "맞음" : "틀림"}</b>}</div>; };
  const question = (p: CylinderProblem, index: number, key: boolean) => <div className="cylinder-question" key={p.id} data-testid="grade-six-cylinder-question"><span className="cylinder-index">{index + 1}</span><div className="cylinder-figure" aria-label={`밑면 반지름 ${p.radius}${p.unit}, 높이 ${p.height}${p.unit}`}><i className="top" /><i className="body" /><i className="bottom" /><span className="radius">반지름 <b>{p.radius}{p.unit}</b></span><span className="height">높이 <b>{p.height}{p.unit}</b></span></div><div className="cylinder-answers">{answer(p, "surfaceArea", key)}{answer(p, "volume", key)}</div></div>;
  const sheet = (key: boolean) => <div className="a4-sheet counting-sheet cylinder-sheet" style={{ transform: `scale(${scale})` }}><header className="counting-sheet-header"><div className="counting-sheet-title"><span>6학년</span><strong>원기둥{key ? " 정답" : ""}</strong></div><div className="counting-sheet-info"><span>이름 <i /></span><span>날짜 <i /></span><small>문제지 {seed}</small></div></header><p className="cylinder-guide">원주율은 3.14로 계산하세요. 각 원기둥의 겉넓이와 부피를 구하세요.</p><div className="cylinder-grid">{problems.map((p, i) => question(p, i, key))}</div></div>;
  return <main className="counting-page multiplication-page"><div className="counting-toolbar"><a className="counting-back" href="/arithmetic">← 연산</a><div className="counting-progress"><strong>{correct}<small>/8 정답</small></strong></div><div className="toolbar"><button className="button secondary" onClick={fresh}>새 문제</button><button className="button ghost" onClick={reset}>다시 풀기</button><div className="print-control"><button className="button ghost print-button" onClick={() => setPrintOpen(!printOpen)}>인쇄</button>{printOpen && <div className="print-menu"><button onClick={() => print("worksheet")}>문제지만 인쇄</button><button onClick={() => print("answers")}>답지만 인쇄</button><button onClick={() => print("both")}>문제지+답지 인쇄</button></div>}</div><button className="button primary" onClick={check}>전체 채점</button></div></div><div className="a4-stage counting-a4-stage worksheet-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(false)}</div><div className="a4-stage counting-a4-stage answer-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(true)}</div></main>;
}
