"use client";
import { useEffect, useMemo, useState } from "react";
import { createGradeSixProportionSet, normalizeProportionAnswer } from "../../../lib/grade-six-proportion";
import type { ProportionProblem } from "../../../lib/grade-six-proportion";
type PrintMode = "worksheet" | "answers" | "both";
export default function GradeSixProportionPage() {
  const [seed, setSeed] = useState(20260722); const [answers, setAnswers] = useState<Record<string, string>>({}); const [results, setResults] = useState<Record<string, boolean>>({}); const [scale, setScale] = useState(.6); const [printOpen, setPrintOpen] = useState(false); const problems = useMemo(() => createGradeSixProportionSet(seed), [seed]); const correct = Object.values(results).filter(Boolean).length;
  useEffect(() => { const fit = () => setScale(Math.min((innerWidth - 32) / 794, 1)); fit(); addEventListener("resize", fit); return () => removeEventListener("resize", fit); }, []);
  const update = (id: string, value: string) => { setAnswers((now) => ({ ...now, [id]: value.slice(0, 16) })); setResults((now) => { const next = { ...now }; delete next[id]; return next; }); };
  const reset = () => { setAnswers({}); setResults({}); }; const fresh = () => { if (Object.keys(answers).length && !confirm("답이 사라집니다. 새 문제를 만들까요?")) return; setSeed((Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0); reset(); };
  const check = () => setResults(Object.fromEntries(problems.map((problem) => [problem.id, normalizeProportionAnswer(answers[problem.id] ?? "") === normalizeProportionAnswer(problem.answer)])));
  const print = (mode: PrintMode) => { setPrintOpen(false); document.documentElement.dataset.printMode = mode; addEventListener("afterprint", () => delete document.documentElement.dataset.printMode, { once: true }); requestAnimationFrame(() => window.print()); };
  const question = (problem: ProportionProblem, index: number, key: boolean) => <div className={`multiplication-question mixed-calculation-question${problem.id in results ? results[problem.id] ? " is-correct" : " is-wrong" : ""}`} key={problem.id} data-testid="grade-six-proportion-question"><span className="mixed-calculation-index">{index + 1}</span><div className="mixed-calculation-expression"><strong>{problem.prompt}</strong><span>=</span>{key ? <span className="mixed-calculation-static-answer">{problem.answer}</span> : <input className="mixed-calculation-input" type="text" value={answers[problem.id] ?? ""} onChange={(event) => update(problem.id, event.target.value)} aria-label={`${index + 1}번 ${problem.guide}`} />}</div>{!key && problem.id in results && <span className={`counting-result ${results[problem.id] ? "correct" : "wrong"}`}>{results[problem.id] ? "맞음" : "틀림"}</span>}</div>;
  const sheet = (key: boolean) => <div className="a4-sheet counting-sheet mixed-calculation-sheet" style={{ transform: `scale(${scale})` }}><header className="counting-sheet-header"><div className="counting-sheet-title"><span>6학년</span><strong>비례식{key ? " 정답" : ""}</strong></div><div className="counting-sheet-info"><span>이름 <i /></span><span>날짜 <i /></span><small>문제지 {seed}</small></div></header><p className="mixed-calculation-guide">비의 순서를 확인하고, 답은 쉼표 또는 콜론(:)을 사용하여 쓰세요.</p><div className="mixed-calculation-grid">{problems.map((p, i) => question(p, i, key))}</div></div>;
  return <main className="counting-page multiplication-page"><div className="counting-toolbar"><a className="counting-back" href="/arithmetic">← 연산</a><div className="counting-progress"><strong>{correct}<small>/6 정답</small></strong></div><div className="toolbar"><button className="button secondary" onClick={fresh}>새 문제</button><button className="button ghost" onClick={reset}>다시 풀기</button><div className="print-control"><button className="button ghost print-button" onClick={() => setPrintOpen(!printOpen)}>인쇄</button>{printOpen && <div className="print-menu"><button onClick={() => print("worksheet")}>문제지만 인쇄</button><button onClick={() => print("answers")}>답지만 인쇄</button><button onClick={() => print("both")}>문제지+답지 인쇄</button></div>}</div><button className="button primary" onClick={check}>전체 채점</button></div></div><div className="a4-stage counting-a4-stage worksheet-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(false)}</div><div className="a4-stage counting-a4-stage answer-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(true)}</div></main>;
}
