"use client";
import { useEffect, useMemo, useState } from "react";
import { createGradeSixCircleSet, normalizeCircleAnswer } from "../../../lib/grade-six-circle";
import type { CircleProblem } from "../../../lib/grade-six-circle";
type PrintMode = "worksheet" | "answers" | "both";
export default function GradeSixCirclePage() {
  const [seed, setSeed] = useState(20260722); const [answers, setAnswers] = useState<Record<string, string>>({}); const [results, setResults] = useState<Record<string, boolean>>({}); const [scale, setScale] = useState(.6); const [printOpen, setPrintOpen] = useState(false); const problems = useMemo(() => createGradeSixCircleSet(seed), [seed]); const correct = Object.values(results).filter(Boolean).length;
  useEffect(() => { const fit = () => setScale(Math.min((innerWidth - 32) / 794, 1)); fit(); addEventListener("resize", fit); return () => removeEventListener("resize", fit); }, []);
  const update = (id: string, value: string) => { setAnswers((now) => ({ ...now, [id]: value.replace(/[^0-9.]/g, "").slice(0, 8) })); setResults((now) => { const next = { ...now }; delete next[id]; return next; }); };
  const reset = () => { setAnswers({}); setResults({}); }; const fresh = () => { if (Object.values(answers).some(Boolean) && !confirm("답이 사라집니다. 새 문제를 만들까요?")) return; setSeed((Date.now() ^ Math.floor(Math.random() * 0xffffffff)) >>> 0); reset(); }; const check = () => setResults(Object.fromEntries(problems.map((p) => [p.id, normalizeCircleAnswer(answers[p.id] ?? "") === p.answer])));
  const print = (mode: PrintMode) => { setPrintOpen(false); document.documentElement.dataset.printMode = mode; addEventListener("afterprint", () => delete document.documentElement.dataset.printMode, { once: true }); requestAnimationFrame(() => window.print()); };
  const question = (p: CircleProblem, index: number, key: boolean) => { const graded = p.id in results, okay = results[p.id] === true, unit = `${p.unit}${p.target === "넓이" ? "²" : ""}`, line = p.givenLabel === "지름" ? "diameter" : "radius"; return <div className={`circle-question${graded ? okay ? " is-correct" : " is-wrong" : ""}`} key={p.id} data-testid="grade-six-circle-question"><span className="circle-index">{index + 1}</span><div className={`circle-diagram ${line}`} aria-label={`${p.givenLabel} ${p.given}${p.unit}`}><i /><b><small>{p.givenLabel}</small>{p.given}{p.unit}</b></div><div className="circle-equation"><span>{p.target}</span><strong>=</strong>{key ? <em>{p.answer}</em> : <input type="text" inputMode="decimal" value={answers[p.id] ?? ""} onChange={(event) => update(p.id, event.target.value)} aria-label={`${index + 1}번 ${p.target}`} />}<small>{unit}</small></div>{!key && graded && <span className={`counting-result ${okay ? "correct" : "wrong"}`}>{okay ? "맞음" : "틀림"}</span>}</div>; };
  const sheet = (key: boolean) => <div className="a4-sheet counting-sheet circle-sheet" style={{ transform: `scale(${scale})` }}><header className="counting-sheet-header"><div className="counting-sheet-title"><span>6학년</span><strong>원{key ? " 정답" : ""}</strong></div><div className="counting-sheet-info"><span>이름 <i /></span><span>날짜 <i /></span><small>문제지 {seed}</small></div></header><p className="circle-guide">원주율은 3.14로 계산하세요. 단위는 문제에 표시되어 있습니다.</p><div className="circle-grid">{problems.map((p, i) => question(p, i, key))}</div></div>;
  return <main className="counting-page multiplication-page"><div className="counting-toolbar"><a className="counting-back" href="/arithmetic">← 연산</a><div className="counting-progress"><strong>{correct}<small>/8 정답</small></strong></div><div className="toolbar"><button className="button secondary" onClick={fresh}>새 문제</button><button className="button ghost" onClick={reset}>다시 풀기</button><div className="print-control"><button className="button ghost print-button" onClick={() => setPrintOpen(!printOpen)}>인쇄</button>{printOpen && <div className="print-menu"><button onClick={() => print("worksheet")}>문제지만 인쇄</button><button onClick={() => print("answers")}>답지만 인쇄</button><button onClick={() => print("both")}>문제지+답지 인쇄</button></div>}</div><button className="button primary" onClick={check}>전체 채점</button></div></div><div className="a4-stage counting-a4-stage worksheet-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(false)}</div><div className="a4-stage counting-a4-stage answer-stage" style={{ width: 794 * scale, height: 1123 * scale }}>{sheet(true)}</div></main>;
}
