const pieces=[
 {no:'01',era:'baroque',period:'바로크',title:'사계 〈봄〉 1악장',composer:'안토니오 비발디',url:'https://www.youtube.com/results?search_query=Vivaldi+Four+Seasons+Spring+1st+movement',points:['바이올린이 새의 지저귐을 어떻게 흉내 내는지 찾아보세요.','빠르게 반복되는 리듬에서 봄의 활기를 느껴 보세요.'],note:'표제 음악: 음악 밖의 장면이나 이야기를 떠올리게 하는 음악'},
 {no:'02',era:'baroque',period:'바로크',title:'G선상의 아리아',composer:'요한 제바스티안 바흐',url:'https://www.youtube.com/results?search_query=Bach+Air+on+the+G+String',points:['길게 이어지는 선율의 호흡을 따라가 보세요.','현악기의 부드러운 음색 변화를 들어 보세요.'],note:'현악 합주곡 〈관현악 모음곡 3번〉의 한 악장입니다.'},
 {no:'03',era:'classical',period:'고전',title:'교향곡 5번 〈운명〉 1악장',composer:'루트비히 판 베토벤',url:'https://www.youtube.com/results?search_query=Beethoven+Symphony+No+5+1st+movement',points:['“따따따-따” 네 음의 동기를 찾아보세요.','같은 동기가 여러 악기로 어떻게 달라지는지 들어 보세요.'],note:'동기: 곡 전체에서 반복·변형되는 짧은 음악 재료'},
 {no:'04',era:'classical',period:'고전',title:'작은 별 변주곡',composer:'볼프강 아마데우스 모차르트',url:'https://www.youtube.com/results?search_query=Mozart+Twinkle+Twinkle+Little+Star+Variations',points:['익숙한 주제가 몇 번 나오는지 세어 보세요.','빠르기와 리듬이 바뀔 때 느낌도 달라지는지 생각해 보세요.'],note:'변주곡: 하나의 주제를 여러 모습으로 바꾸어 들려주는 곡'},
 {no:'05',era:'romantic',period:'낭만',title:'피아노 5중주 〈송어〉 4악장',composer:'프란츠 슈베르트',url:'https://www.youtube.com/results?search_query=Schubert+Trout+Quintet+4th+movement',points:['경쾌하게 뛰어오르는 반주에서 물고기의 움직임을 상상해 보세요.','주제가 변주될 때 어떤 악기가 앞에 나서는지 찾아보세요.'],note:'실내악: 소수의 연주자가 함께 연주하는 음악'},
 {no:'06',era:'romantic',period:'낭만',title:'호두까기 인형 〈꽃의 왈츠〉',composer:'표트르 차이콥스키',url:'https://www.youtube.com/results?search_query=Tchaikovsky+Nutcracker+Waltz+of+the+Flowers',points:['3박자의 빙글빙글 도는 느낌을 손으로 지휘해 보세요.','하프와 관악기가 만드는 반짝이는 분위기를 들어 보세요.'],note:'왈츠: 강-약-약의 3박자로 춤추듯 흐르는 음악'},
 {no:'07',era:'modern',period:'근현대',title:'동물의 사육제 〈백조〉',composer:'카미유 생상스',url:'https://www.youtube.com/results?search_query=Saint+Saens+The+Swan',points:['첼로의 선율이 백조의 어떤 움직임을 나타내는지 말해 보세요.','피아노 반주의 잔물결 같은 음형을 들어 보세요.'],note:'음색: 악기나 목소리마다 지닌 고유한 소리의 빛깔'},
 {no:'08',era:'modern',period:'근현대',title:'볼레로',composer:'모리스 라벨',url:'https://www.youtube.com/results?search_query=Ravel+Bolero',points:['처음부터 끝까지 반복되는 리듬을 찾아보세요.','점점 커지는 소리와 악기 변화를 기록해 보세요.'],note:'크레셴도: 소리가 점차 커지도록 연주하는 표현'}
];
const quiz=[{q:'〈운명〉 교향곡에서 가장 먼저 귀에 들어오는 것은?',a:['긴 서정 선율','네 음으로 된 짧은 동기','3박자 춤 리듬'],c:1},{q:'〈작은 별 변주곡〉처럼 주제를 여러 모습으로 바꾸는 형식은?',a:['변주곡','교향곡','협주곡'],c:0},{q:'〈볼레로〉를 들으며 주목할 변화는?',a:['점점 작아지는 소리','반복되는 리듬과 점점 커지는 소리','노래하는 합창'],c:1}];
const playlist=document.querySelector('#playlist');function render(filter='all'){playlist.innerHTML=pieces.filter(p=>filter==='all'||p.era===filter).map(p=>`<article class="piece" data-no="${p.no}"><span class="era">${p.period}</span><h3>${p.title}</h3><p class="composer">${p.composer}</p><a class="listen" href="${p.url}" target="_blank" rel="noopener">▶ 감상곡 찾아 듣기</a><ul class="points">${p.points.map(x=>`<li>${x}</li>`).join('')}</ul><p class="note"><b>음악 낱말</b> · ${p.note}</p></article>`).join('')};render();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');render(b.dataset.era)});
const box=document.querySelector('#quiz-box');box.innerHTML=quiz.map((x,i)=>`<div class="question"><p>${i+1}. ${x.q}</p>${x.a.map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}">${a}</label>`).join('')}</div>`).join('');
document.querySelector('#check-answer').onclick=()=>{let score=0;quiz.forEach((x,i)=>{if(+document.querySelector(`input[name=q${i}]:checked`)?.value===x.c)score++});document.querySelector('#result').textContent=`${score} / ${quiz.length} 정답! ${score===3?'훌륭해요. 음악을 듣는 귀가 아주 예리하네요!':'해설을 다시 읽고 한 번 더 들어 볼까요?'}`;document.querySelector('#result').className='correct'};
