window.BODY_EXPLORER_CONFIG = {
    gameId: "digestion",
    messagePrefix: "DIGESTION",
    bestScoreKey: "digestionBestScore",
    namedGreeting: "{name} 탐험가, 음식 알갱이와 함께 소화 여행을 떠나 볼까요?",
    guestGreeting: "음식 알갱이가 되어 입에서 몸 밖까지 소화기관을 여행해 보세요.",
    resetAnnouncement: "새 소화 탐험을 기다립니다.",
    stateLabels: {
        breaking: "잘게 부수는 중",
        moving: "이동 중",
        digesting: "소화 중",
        absorbing: "흡수 중",
        remaining: "남은 찌꺼기"
    },
    resultMessages: {
        perfect: "모든 소화 경로와 기관의 역할을 한 번에 찾았어요!",
        great: "훌륭해요. 헷갈린 기관의 역할만 다시 보면 완벽해요.",
        good: "소화 여행을 완주했어요. 오답노트로 순서를 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 기관의 역할을 읽고 다시 도전해 봐요."
    }
};

window.BODY_EXPLORER_STAGES = [
    {
        id: "mouth-chewing",
        shortLabel: "입",
        location: "입",
        scene: "mouth",
        oxygen: "breaking",
        chapter: "소화의 시작",
        mission: "큰 음식 덩어리를 이로 잘게 부수세요.",
        fact: "소화는 입에서 시작합니다. 이는 음식을 잘게 부수어 삼키기 쉽게 만듭니다.",
        question: "입에서 이가 하는 가장 중요한 일은?",
        choices: ["음식을 잘게 씹는다", "영양소를 피로 보낸다", "음식의 물을 흡수한다"],
        answer: "음식을 잘게 씹는다",
        hint: "딱딱한 음식을 먹을 때 이를 어떻게 사용하는지 떠올려 보세요.",
        explanation: "이는 음식을 작은 조각으로 부수어 침과 잘 섞이고 삼키기 쉽게 합니다."
    },
    {
        id: "mouth-saliva",
        shortLabel: "침",
        location: "입속의 침",
        scene: "mouth",
        oxygen: "breaking",
        chapter: "소화의 시작",
        mission: "잘게 씹은 음식에 침을 골고루 섞으세요.",
        fact: "침은 음식을 촉촉하게 만들고, 음식의 소화를 시작하도록 돕습니다.",
        question: "침이 음식과 섞이면 생기는 변화는?",
        choices: ["삼키기 쉬워지고 소화가 시작된다", "음식이 바로 피가 된다", "음식이 다시 커진다"],
        answer: "삼키기 쉬워지고 소화가 시작된다",
        hint: "마른 과자를 오래 씹으면 촉촉해지는 것을 생각해 보세요.",
        explanation: "침은 음식을 부드럽게 하고 소화가 시작되도록 돕습니다."
    },
    {
        id: "swallow-esophagus",
        shortLabel: "삼키기",
        location: "목과 식도 입구",
        scene: "esophagus",
        oxygen: "moving",
        chapter: "위로 가는 길",
        mission: "잘게 씹은 음식을 위로 이어지는 알맞은 통로에 보내세요.",
        fact: "삼킨 음식은 식도를 지나 위로 이동합니다. 식도는 입과 위를 이어 주는 긴 관입니다.",
        question: "입에서 위까지 음식을 보내는 통로는?",
        choices: ["식도", "기도", "혈관"],
        answer: "식도",
        hint: "이름에 ‘먹을 식(食)’이 들어가는 관이에요.",
        explanation: "입 → 식도 → 위 순서로 음식이 이동합니다."
    },
    {
        id: "esophagus-movement",
        shortLabel: "식도",
        location: "식도",
        scene: "esophagus",
        oxygen: "moving",
        chapter: "위로 가는 길",
        mission: "식도 벽의 움직임을 타고 위까지 내려가세요.",
        fact: "식도 벽의 근육이 차례로 오므라들고 펴지면서 음식을 위쪽에서 아래쪽으로 밀어냅니다.",
        question: "식도에서 음식이 위로 이동하는 까닭은?",
        choices: ["식도 벽의 근육이 음식을 밀기 때문에", "이가 계속 음식을 씹기 때문에", "폐가 음식을 끌어당기기 때문에"],
        answer: "식도 벽의 근육이 음식을 밀기 때문에",
        hint: "식도는 가만히 있는 빨대가 아니라 움직이는 관이에요.",
        explanation: "식도 벽의 근육 운동이 음식을 위까지 밀어 보냅니다."
    },
    {
        id: "stomach-mixing",
        shortLabel: "위",
        location: "위",
        scene: "stomach",
        oxygen: "digesting",
        chapter: "음식을 섞는 주머니",
        mission: "음식을 소화액과 섞어 더 작은 상태로 만드세요.",
        fact: "위는 주머니 모양의 기관입니다. 위 벽이 움직이며 음식과 소화액을 섞습니다.",
        question: "위에서 주로 일어나는 일은?",
        choices: ["음식과 소화액을 섞는다", "산소를 받아들인다", "오줌을 저장한다"],
        answer: "음식과 소화액을 섞는다",
        hint: "위는 음식을 잠시 담아 두고 주물러 섞는 곳이에요.",
        explanation: "위는 음식물을 소화액과 섞어 죽처럼 만든 뒤 작은창자로 조금씩 보냅니다."
    },
    {
        id: "digestive-helpers",
        shortLabel: "소화액",
        location: "작은창자 입구",
        scene: "stomach",
        oxygen: "digesting",
        chapter: "소화를 돕는 기관",
        mission: "간과 이자에서 온 소화액의 도움을 받으세요.",
        fact: "간과 이자는 음식의 소화를 돕는 액체를 만들어 작은창자로 보냅니다.",
        question: "작은창자에서 음식의 소화를 돕는 기관끼리 묶인 것은?",
        choices: ["간과 이자", "심장과 폐", "콩팥과 방광"],
        answer: "간과 이자",
        hint: "배의 위쪽에 있으며 소화액을 만들어 보내는 두 기관이에요.",
        explanation: "간과 이자는 소화를 돕는 액체를 작은창자로 보내 음식이 더 잘게 나뉘도록 돕습니다."
    },
    {
        id: "small-intestine-digestion",
        shortLabel: "작은창자",
        location: "작은창자",
        scene: "intestine",
        oxygen: "digesting",
        chapter: "소화의 마무리",
        mission: "몸이 사용할 수 있도록 음식을 작은 영양소로 나누세요.",
        fact: "작은창자는 길고 구불구불합니다. 이곳에서 음식의 소화가 마무리됩니다.",
        question: "음식의 소화가 대부분 마무리되는 곳은?",
        choices: ["작은창자", "식도", "큰창자 끝"],
        answer: "작은창자",
        hint: "위 다음에 이어지는 길고 구불구불한 기관이에요.",
        explanation: "위에서 온 음식은 작은창자에서 소화액과 섞이며 몸이 흡수할 수 있는 작은 영양소가 됩니다."
    },
    {
        id: "small-intestine-absorption",
        shortLabel: "영양소",
        location: "작은창자 벽",
        scene: "absorption",
        oxygen: "absorbing",
        chapter: "영양소 흡수",
        mission: "작아진 영양소를 작은창자 벽을 지나 혈액으로 보내세요.",
        fact: "소화된 영양소는 대부분 작은창자 벽을 지나 혈액으로 흡수됩니다.",
        question: "소화된 영양소가 주로 흡수되는 곳은?",
        choices: ["작은창자", "식도", "입"],
        answer: "작은창자",
        hint: "소화를 마무리한 뒤 바로 영양소를 흡수하는 기관이에요.",
        explanation: "작은창자에서 흡수된 영양소는 혈액을 따라 온몸의 필요한 곳으로 이동합니다."
    },
    {
        id: "large-intestine-water",
        shortLabel: "큰창자",
        location: "큰창자",
        scene: "large",
        oxygen: "remaining",
        chapter: "남은 물 흡수",
        mission: "소화되고 남은 찌꺼기에서 물을 흡수하세요.",
        fact: "큰창자는 소화되고 남은 찌꺼기에서 물을 흡수합니다.",
        question: "큰창자가 하는 중요한 일은?",
        choices: ["남은 찌꺼기에서 물을 흡수한다", "음식을 이로 씹는다", "피를 온몸으로 보낸다"],
        answer: "남은 찌꺼기에서 물을 흡수한다",
        hint: "작은창자에서 영양소를 흡수한 뒤 남은 것에서 필요한 것을 더 가져와요.",
        explanation: "큰창자가 물을 흡수하고 나면 남은 찌꺼기가 점차 단단해집니다."
    },
    {
        id: "body-exit",
        shortLabel: "몸 밖",
        location: "소화기관의 마지막 길",
        scene: "large",
        oxygen: "remaining",
        chapter: "소화 여행 완성",
        mission: "몸에서 쓰이지 않은 찌꺼기를 몸 밖으로 내보내세요.",
        fact: "영양소와 물이 흡수된 뒤 남은 찌꺼기는 큰창자 끝을 지나 항문으로 배출됩니다.",
        question: "소화되고 남은 찌꺼기가 몸 밖으로 나가는 곳은?",
        choices: ["항문", "입", "식도"],
        answer: "항문",
        hint: "소화기관의 가장 마지막 출구예요.",
        explanation: "입에서 시작한 음식의 여행은 항문에서 끝납니다. 필요한 영양소는 이미 몸속에 흡수되었습니다."
    }
];
