window.BODY_EXPLORER_CONFIG = {
    gameId: "digestion",
    messagePrefix: "DIGESTION",
    bestScoreKey: "digestionBestScore",
    namedGreeting: "{name} 탐험가, 음식 알갱이와 함께 소화 여행을 떠나 볼까요?",
    guestGreeting: "음식 알갱이가 되어 입에서 몸 밖까지 소화기관을 여행해 보세요.",
    resetAnnouncement: "새 소화 탐험을 기다립니다.",
    stateLabels: {
        breaking: "잘게 부수는 중",
        moving: "이동 중",
        digesting: "소화 중",
        absorbing: "흡수 중",
        remaining: "남은 찌꺼기"
    },
    resultMessages: {
        perfect: "모든 소화 경로와 기관의 역할을 한 번에 찾았어요!",
        great: "훌륭해요. 헷갈린 기관의 역할만 다시 보면 완벽해요.",
        good: "소화 여행을 완주했어요. 오답노트로 순서를 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 기관의 역할을 읽고 다시 도전해 봐요."
    }
};

window.BODY_EXPLORER_STAGES = [
    {
        id: "mouth-chewing",
        shortLabel: "입",
        location: "입",
        scene: "mouth",
        oxygen: "breaking",
        chapter: "소화의 시작",
        mission: "큰 음식 덩어리를 이로 잘게 부수세요.",
        fact: "소화는 입에서 시작합니다. 이는 음식을 잘게 부수어 삼키기 쉽게 만듭니다.",
        question: "같은 음식을 충분히 씹었을 때 소화가 더 쉬워지는 까닭은?",
        choices: ["잘게 부서져 침·소화액과 닿는 면이 넓어지기 때문에", "씹는 힘이 위와 작은창자의 운동을 대신하기 때문에", "씹는 동안 영양소가 입에서 혈액으로 흡수되기 때문에"],
        answer: "잘게 부서져 침·소화액과 닿는 면이 넓어지기 때문에",
        hint: "큰 얼음 한 덩이와 잘게 부순 얼음 중 어느 쪽이 주변과 더 많이 닿는지 비교해 보세요.",
        explanation: "이는 음식을 작은 조각으로 부수어 침과 소화액이 닿는 면을 넓히고, 삼키기 쉽게 합니다."
    },
    {
        id: "mouth-saliva",
        shortLabel: "침",
        location: "입속의 침",
        scene: "mouth",
        oxygen: "breaking",
        chapter: "소화의 시작",
        mission: "잘게 씹은 음식에 침을 골고루 섞으세요.",
        fact: "침은 음식을 촉촉하게 만들고, 밥이나 빵에 많은 녹말의 소화를 시작하도록 돕습니다.",
        question: "밥을 오래 씹으면 부드러워지고 약간 단맛이 나는 현상과 가장 관계 깊은 것은?",
        choices: ["침의 작용으로 녹말의 소화가 시작된다", "이가 녹말을 단맛 나는 물질로 바꾼다", "혀가 음식의 영양소를 흡수해 단맛을 느낀다"],
        answer: "침의 작용으로 녹말의 소화가 시작된다",
        hint: "이는 잘게 부수고, 혀는 맛을 느낍니다. 음식에 섞이는 액체의 작용을 생각해 보세요.",
        explanation: "침은 음식을 부드럽게 할 뿐 아니라 녹말의 소화를 시작하도록 돕습니다."
    },
    {
        id: "swallow-esophagus",
        shortLabel: "삼키기",
        location: "목과 식도 입구",
        scene: "esophagus",
        oxygen: "moving",
        chapter: "위로 가는 길",
        mission: "잘게 씹은 음식을 위로 이어지는 알맞은 통로에 보내세요.",
        fact: "삼킨 음식은 식도를 지나 위로 이동합니다. 식도는 입과 위를 이어 주는 긴 관입니다.",
        question: "삼킨 음식이 이동하는 경로를 바르게 나타낸 것은?",
        choices: ["입과 목 → 식도 → 위", "입과 목 → 기관 → 위", "입과 목 → 식도 → 작은창자"],
        answer: "입과 목 → 식도 → 위",
        hint: "공기가 가는 기관과 음식이 가는 식도를 구별하고, 위를 건너뛰지 않았는지 살펴보세요.",
        explanation: "입 → 식도 → 위 순서로 음식이 이동합니다."
    },
    {
        id: "esophagus-movement",
        shortLabel: "식도",
        location: "식도",
        scene: "esophagus",
        oxygen: "moving",
        chapter: "위로 가는 길",
        mission: "식도 벽의 움직임을 타고 위까지 내려가세요.",
        fact: "식도 벽의 근육이 차례로 오므라들고 펴지면서 음식을 위쪽에서 아래쪽으로 밀어냅니다.",
        question: "누운 자세에서도 삼킨 음식이 위로 이동할 수 있는 가장 알맞은 까닭은?",
        choices: ["식도 벽의 근육이 차례로 움직여 음식을 밀기 때문에", "중력이 자세와 관계없이 항상 위쪽으로 음식을 당기기 때문에", "위의 소화액이 식도 속 음식을 빨아들이기 때문에"],
        answer: "식도 벽의 근육이 차례로 움직여 음식을 밀기 때문에",
        hint: "음식의 이동이 중력에만 의존한다면 누웠을 때 어떻게 될지 생각해 보세요.",
        explanation: "식도 벽의 근육 운동이 음식을 위까지 밀어 보냅니다."
    },
    {
        id: "stomach-mixing",
        shortLabel: "위",
        location: "위",
        scene: "stomach",
        oxygen: "digesting",
        chapter: "음식을 섞는 주머니",
        mission: "음식을 소화액과 섞어 더 작은 상태로 만드세요.",
        fact: "위는 주머니 모양의 기관입니다. 위 벽이 움직이며 음식과 소화액을 섞습니다.",
        question: "주머니 모양이고 근육으로 된 위의 특징과 기능을 바르게 연결한 것은?",
        choices: ["음식을 잠시 담고 움직여 소화액과 섞는다", "소화된 영양소를 대부분 혈액으로 흡수한다", "남은 찌꺼기에서 물을 주로 흡수한다"],
        answer: "음식을 잠시 담고 움직여 소화액과 섞는다",
        hint: "다른 두 기능은 작은창자와 큰창자의 대표적인 역할입니다.",
        explanation: "위는 음식물을 소화액과 섞어 죽처럼 만든 뒤 작은창자로 조금씩 보냅니다."
    },
    {
        id: "digestive-helpers",
        shortLabel: "소화액",
        location: "작은창자 입구",
        scene: "stomach",
        oxygen: "digesting",
        chapter: "소화를 돕는 기관",
        mission: "간과 이자에서 온 소화액의 도움을 받으세요.",
        fact: "간과 이자는 음식의 소화를 돕는 액체를 만들어 작은창자로 보냅니다.",
        question: "간과 이자에서 나온 소화액이 작은창자에 도착하지 못한다면 가장 직접적인 변화는?",
        choices: ["작은창자에서 음식물의 소화가 원활하지 않다", "식도에서 음식물을 미는 운동이 멈춘다", "큰창자에서 물을 흡수하는 양이 바로 늘어난다"],
        answer: "작은창자에서 음식물의 소화가 원활하지 않다",
        hint: "두 기관이 소화액을 보내는 목적지가 어디인지 연결해 보세요.",
        explanation: "간과 이자는 소화를 돕는 액체를 작은창자로 보내 음식이 더 잘게 나뉘도록 돕습니다."
    },
    {
        id: "small-intestine-digestion",
        shortLabel: "작은창자",
        location: "작은창자",
        scene: "intestine",
        oxygen: "digesting",
        chapter: "소화의 마무리",
        mission: "몸이 사용할 수 있도록 음식을 작은 영양소로 나누세요.",
        fact: "작은창자는 길고 구불구불합니다. 이곳에서 음식의 소화가 마무리됩니다.",
        question: "작은창자가 길고 구불구불한 모양인 것이 소화에 주는 이점은?",
        choices: ["소화액과 충분히 섞이고 영양소가 흡수될 기회가 늘어난다", "위가 맡은 음식 저장 기능을 대부분 대신할 수 있다", "큰창자처럼 남은 찌꺼기의 물만 골라 흡수하기 쉽다"],
        answer: "소화액과 충분히 섞이고 영양소가 흡수될 기회가 늘어난다",
        hint: "음식물이 지나가는 길이 길어질 때 소화와 흡수에 쓸 수 있는 시간과 면적을 생각해 보세요.",
        explanation: "위에서 온 음식은 작은창자에서 소화액과 섞이며 몸이 흡수할 수 있는 작은 영양소가 됩니다."
    },
    {
        id: "small-intestine-absorption",
        shortLabel: "영양소",
        location: "작은창자 벽",
        scene: "absorption",
        oxygen: "absorbing",
        chapter: "영양소 흡수",
        mission: "작아진 영양소를 작은창자 벽을 지나 혈액으로 보내세요.",
        fact: "소화된 영양소는 대부분 작은창자 벽을 지나 혈액으로 흡수됩니다.",
        question: "작은창자 벽을 통과한 영양소의 다음 이동 경로로 알맞은 것은?",
        choices: ["혈액을 따라 온몸의 필요한 곳으로 이동한다", "위로 돌아가 소화액과 다시 섞인다", "큰창자로 이동해 남은 찌꺼기와 함께 저장된다"],
        answer: "혈액을 따라 온몸의 필요한 곳으로 이동한다",
        hint: "흡수는 영양소가 소화관 안쪽에서 몸속의 운반 통로로 들어가는 과정입니다.",
        explanation: "작은창자에서 흡수된 영양소는 혈액을 따라 온몸의 필요한 곳으로 이동합니다."
    },
    {
        id: "large-intestine-water",
        shortLabel: "큰창자",
        location: "큰창자",
        scene: "large",
        oxygen: "remaining",
        chapter: "남은 물 흡수",
        mission: "소화되고 남은 찌꺼기에서 물을 흡수하세요.",
        fact: "큰창자는 소화되고 남은 찌꺼기에서 물을 흡수합니다.",
        question: "큰창자에서 평소보다 물을 적게 흡수한다면 남은 찌꺼기는 어떻게 달라질까요?",
        choices: ["물을 더 많이 포함해 비교적 묽어진다", "물을 더 적게 포함해 더욱 단단해진다", "영양소가 다시 큰 분자로 합쳐진다"],
        answer: "물을 더 많이 포함해 비교적 묽어진다",
        hint: "큰창자가 가져가지 못한 물이 찌꺼기 쪽에 얼마나 남을지 생각해 보세요.",
        explanation: "큰창자가 물을 흡수하고 나면 남은 찌꺼기가 점차 단단해집니다."
    },
    {
        id: "body-exit",
        shortLabel: "몸 밖",
        location: "소화기관의 마지막 길",
        scene: "large",
        oxygen: "remaining",
        chapter: "소화 여행 완성",
        mission: "몸에서 쓰이지 않은 찌꺼기를 몸 밖으로 내보내세요.",
        fact: "영양소와 물이 흡수된 뒤 남은 찌꺼기는 큰창자 끝을 지나 항문으로 배출됩니다.",
        question: "음식물이 지나가는 소화관의 순서를 바르게 나타낸 것은?",
        choices: ["입 → 식도 → 위 → 작은창자 → 큰창자 → 항문", "입 → 위 → 식도 → 작은창자 → 큰창자 → 항문", "입 → 식도 → 작은창자 → 위 → 큰창자 → 항문"],
        answer: "입 → 식도 → 위 → 작은창자 → 큰창자 → 항문",
        hint: "위와 식도의 순서, 위와 작은창자의 순서를 각각 확인해 보세요.",
        explanation: "입에서 시작한 음식의 여행은 항문에서 끝납니다. 필요한 영양소는 이미 몸속에 흡수되었습니다."
    }
];
