window.BODY_EXPLORER_CONFIG = {
    gameId: "circulation",
    messagePrefix: "CIRCULATION",
    bestScoreKey: "circulationBestScore",
    namedGreeting: "{name} 탐험가, 적혈구와 함께 혈액순환 한 바퀴를 출발해 볼까요?",
    guestGreeting: "적혈구가 되어 심장과 폐, 온몸을 직접 한 바퀴 돌아보세요.",
    resetAnnouncement: "새 혈액순환 탐험을 기다립니다.",
    stateLabels: {
        low: "산소 적음",
        exchange: "기체 교환 중",
        rich: "산소 풍부"
    },
    resultMessages: {
        perfect: "모든 혈액순환 경로를 한 번에 찾았어요!",
        great: "훌륭해요. 막혔던 경로만 다시 확인하면 완벽해요.",
        good: "한 바퀴를 완주했어요. 오답노트로 순서를 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 경로를 읽고 다시 도전해 봐요."
    }
};

window.CIRCULATION_STAGES = [
    {
        id: "body-return",
        shortLabel: "온몸",
        location: "온몸의 모세혈관",
        scene: "body",
        oxygen: "low",
        chapter: "온몸 → 심장",
        mission: "산소를 건넨 뒤 생긴 이산화탄소를 싣고 심장으로 돌아가세요.",
        fact: "조직에 산소를 전달한 혈액은 이산화탄소를 받아 작은 정맥들을 거쳐 대정맥으로 모입니다. 산소가 적은 혈액도 실제로는 파란색이 아니라 짙은 붉은색입니다.",
        question: "온몸에서 돌아온 혈액이 심장으로 들어갈 때 지나는 가장 큰 정맥은?",
        choices: ["대정맥", "대동맥", "폐동맥"],
        answer: "대정맥",
        hint: "정맥은 혈액을 심장 쪽으로 되돌려 보내는 혈관이에요.",
        explanation: "대정맥은 온몸에서 돌아온 산소가 적은 혈액을 우심방으로 운반합니다."
    },
    {
        id: "right-atrium",
        shortLabel: "우심방",
        location: "대정맥과 우심방",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 오른쪽",
        mission: "대정맥을 빠져나와 처음 만나는 심장 방으로 들어가세요.",
        fact: "심방은 심장 위쪽의 두 방입니다. 대정맥에서 온 혈액은 먼저 심장의 오른쪽 위 방에 모입니다.",
        question: "대정맥에서 온 혈액이 가장 먼저 들어가는 심장 방은?",
        choices: ["우심방", "좌심방", "좌심실"],
        answer: "우심방",
        hint: "온몸에서 돌아온 혈액은 심장의 오른쪽 위 방에 먼저 도착해요.",
        explanation: "대정맥 → 우심방 순서입니다. 우심방은 산소가 적은 혈액을 받아 우심실로 넘깁니다."
    },
    {
        id: "tricuspid",
        shortLabel: "삼첨판",
        location: "우심방과 우심실 사이",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 오른쪽",
        mission: "혈액이 뒤로 흐르지 않도록 한 방향으로 열리는 문을 통과하세요.",
        fact: "판막은 혈액이 거꾸로 흐르는 것을 막는 문입니다. 우심방과 우심실 사이에는 삼첨판이 있습니다.",
        question: "우심방에서 우심실로 갈 때 통과하는 판막은?",
        choices: ["삼첨판", "대동맥판", "이첨판(승모판)"],
        answer: "삼첨판",
        hint: "이 판막은 오른쪽 심방과 오른쪽 심실 사이에 있어요.",
        explanation: "삼첨판이 열리면 혈액이 우심방에서 우심실로 흐르고, 닫히면 역류를 막습니다."
    },
    {
        id: "pulmonary-artery",
        shortLabel: "폐동맥",
        location: "우심실과 폐동맥",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 → 폐",
        mission: "우심실의 수축을 타고 산소를 얻으러 폐로 출발하세요.",
        fact: "동맥은 산소량이 아니라 흐르는 방향으로 구분합니다. 심장에서 멀어지는 혈관이 동맥이므로, 폐동맥에는 산소가 적은 혈액이 흐릅니다.",
        question: "우심실에서 폐로 혈액을 보내는 혈관은?",
        choices: ["폐동맥", "폐정맥", "대정맥"],
        answer: "폐동맥",
        hint: "심장에서 폐 쪽으로 멀어지는 혈관이므로 ‘동맥’이에요.",
        explanation: "우심실 → 폐동맥 → 폐 순서입니다. 폐동맥은 산소가 적은 혈액을 운반하는 특별한 동맥입니다."
    },
    {
        id: "alveoli",
        shortLabel: "폐포",
        location: "폐포를 감싼 모세혈관",
        scene: "lung",
        oxygen: "exchange",
        chapter: "폐순환의 중심",
        mission: "폐포에서 이산화탄소를 내려놓고 산소를 받아오세요.",
        fact: "폐포와 모세혈관의 얇은 벽 사이에서 기체가 이동합니다. 산소는 폐포에서 혈액으로, 이산화탄소는 혈액에서 폐포로 이동합니다.",
        question: "폐포에서 일어나는 기체 교환을 바르게 나타낸 것은?",
        choices: ["산소는 혈액으로, 이산화탄소는 폐포로", "산소와 이산화탄소가 모두 혈액으로", "산소는 폐포로, 이산화탄소는 혈액으로"],
        answer: "산소는 혈액으로, 이산화탄소는 폐포로",
        hint: "우리가 들이마신 산소는 혈액에 실려 온몸으로 가야 해요.",
        explanation: "폐포에서 산소를 얻은 적혈구는 밝은 붉은색을 띠며 다시 심장으로 향합니다."
    },
    {
        id: "pulmonary-vein",
        shortLabel: "폐정맥",
        location: "폐정맥과 좌심방",
        scene: "body",
        oxygen: "rich",
        chapter: "폐 → 심장",
        mission: "새로 얻은 산소를 싣고 심장의 왼쪽 위 방으로 돌아가세요.",
        fact: "정맥은 혈액을 심장 쪽으로 운반합니다. 폐정맥에는 폐에서 산소를 얻은 혈액이 흐릅니다.",
        question: "폐에서 산소를 얻은 혈액이 좌심방으로 돌아가는 혈관은?",
        choices: ["폐정맥", "폐동맥", "대동맥"],
        answer: "폐정맥",
        hint: "폐에서 심장으로 ‘돌아오는’ 혈관이에요.",
        explanation: "폐 → 폐정맥 → 좌심방 순서입니다. 폐정맥은 산소가 많은 혈액을 운반하는 특별한 정맥입니다."
    },
    {
        id: "mitral",
        shortLabel: "이첨판",
        location: "좌심방과 좌심실 사이",
        scene: "heart",
        oxygen: "rich",
        chapter: "심장 왼쪽",
        mission: "좌심실로 내려가는 한 방향 판막을 통과하세요.",
        fact: "좌심방과 좌심실 사이의 판막은 이첨판이며 승모판이라고도 합니다. 이 판막도 혈액의 역류를 막습니다.",
        question: "좌심방에서 좌심실로 갈 때 통과하는 판막은?",
        choices: ["이첨판(승모판)", "삼첨판", "폐동맥판"],
        answer: "이첨판(승모판)",
        hint: "왼쪽 심방과 왼쪽 심실 사이에 있는 판막이에요.",
        explanation: "이첨판(승모판)이 열리면 산소가 많은 혈액이 좌심방에서 좌심실로 이동합니다."
    },
    {
        id: "left-ventricle",
        shortLabel: "좌심실",
        location: "좌심실",
        scene: "heart",
        oxygen: "rich",
        chapter: "온몸으로 보낼 준비",
        mission: "강한 수축을 타고 온몸으로 나갈 준비를 하세요.",
        fact: "좌심실은 혈액을 온몸까지 밀어내야 하므로 네 개의 심장 방 가운데 근육벽이 가장 두껍습니다.",
        question: "산소가 많은 혈액을 강하게 수축해 온몸으로 보내는 심장 방은?",
        choices: ["좌심실", "우심실", "우심방"],
        answer: "좌심실",
        hint: "심장의 왼쪽 아래쪽에 있으며 근육벽이 가장 두꺼워요.",
        explanation: "좌심실의 강한 수축이 온몸으로 혈액을 보낼 높은 압력을 만듭니다."
    },
    {
        id: "aorta",
        shortLabel: "대동맥",
        location: "대동맥판과 대동맥",
        scene: "body",
        oxygen: "rich",
        chapter: "심장 → 온몸",
        mission: "심장에서 나가는 가장 큰 동맥을 타고 온몸으로 출발하세요.",
        fact: "좌심실에서 나온 혈액은 대동맥판을 지나 우리 몸에서 가장 큰 동맥인 대동맥으로 들어갑니다.",
        question: "좌심실에서 나온 혈액이 온몸으로 갈 때 들어가는 가장 큰 동맥은?",
        choices: ["대동맥", "대정맥", "폐정맥"],
        answer: "대동맥",
        hint: "이름에 ‘큰 대(大)’가 들어가는 가장 큰 동맥이에요.",
        explanation: "좌심실 → 대동맥판 → 대동맥 순서로 이동한 뒤 여러 동맥으로 갈라집니다."
    },
    {
        id: "tissue-exchange",
        shortLabel: "모세혈관",
        location: "온몸 조직의 모세혈관",
        scene: "body",
        oxygen: "rich",
        chapter: "온몸순환 완성",
        mission: "마지막으로 조직세포에 산소를 전달해 한 바퀴를 완성하세요.",
        fact: "동맥은 더 작은 세동맥으로 갈라지고 모세혈관에 이어집니다. 얇은 모세혈관 벽을 사이에 두고 산소와 영양소가 조직으로 전달됩니다.",
        question: "혈액과 조직세포 사이에서 산소·영양소·노폐물이 실제로 교환되는 혈관은?",
        choices: ["모세혈관", "대동맥", "대정맥"],
        answer: "모세혈관",
        hint: "벽이 매우 얇고 온몸 구석구석에 퍼져 있는 가장 가는 혈관이에요.",
        explanation: "모세혈관에서 산소를 전달한 혈액은 다시 정맥 쪽으로 모여 순환을 반복합니다."
    }
];

window.BODY_EXPLORER_STAGES = window.CIRCULATION_STAGES;
