window.BODY_EXPLORER_CONFIG = {
    gameId: "circulation",
    messagePrefix: "CIRCULATION",
    bestScoreKey: "circulationBestScore",
    experienceType: "circulation-explorer",
    namedGreeting: "{name} 탐험가, 적혈구와 함께 혈액순환 한 바퀴를 출발해 볼까요?",
    guestGreeting: "적혈구가 되어 심장과 폐, 온몸을 직접 한 바퀴 돌아보세요.",
    resetAnnouncement: "새 혈액순환 탐험을 기다립니다.",
    stateLabels: {
        low: "산소 적음",
        exchange: "기체 교환 중",
        rich: "산소 풍부"
    },
    resultMessages: {
        perfect: "모든 혈액순환 경로를 한 번에 찾았어요!",
        great: "훌륭해요. 막혔던 경로만 다시 확인하면 완벽해요.",
        good: "한 바퀴를 완주했어요. 오답노트로 순서를 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 경로를 읽고 다시 도전해 봐요."
    }
};

window.CIRCULATION_STAGES = [
    {
        id: "body-return",
        target: "body-return",
        shortLabel: "온몸",
        location: "온몸의 모세혈관",
        scene: "body",
        oxygen: "low",
        chapter: "온몸 → 심장",
        mission: "산소를 건넨 뒤 생긴 이산화탄소를 싣고 심장으로 돌아가세요.",
        fact: "조직에 산소를 전달한 혈액은 이산화탄소를 받아 작은 정맥들을 거쳐 대정맥으로 모입니다. 산소가 적은 혈액도 실제로는 파란색이 아니라 짙은 붉은색입니다.",
        question: "온몸에서 돌아온 혈액이 심장으로 들어갈 때 지나는 가장 큰 정맥은?",
        choices: ["대정맥", "대동맥", "폐동맥"],
        answer: "대정맥",
        hint: "정맥은 혈액을 심장 쪽으로 되돌려 보내는 혈관이에요.",
        explanation: "대정맥은 온몸에서 돌아온 산소가 적은 혈액을 우심방으로 운반합니다."
    },
    {
        id: "right-atrium",
        target: "right-atrium",
        shortLabel: "우심방",
        location: "대정맥과 우심방",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 오른쪽",
        mission: "대정맥을 빠져나와 처음 만나는 심장 방으로 들어가세요.",
        fact: "심방은 심장 위쪽의 두 방입니다. 대정맥에서 온 혈액은 먼저 심장의 오른쪽 위 방에 모입니다.",
        question: "대정맥에서 온 혈액이 가장 먼저 들어가는 심장 방은?",
        choices: ["우심방", "좌심방", "좌심실"],
        answer: "우심방",
        hint: "온몸에서 돌아온 혈액은 심장의 오른쪽 위 방에 먼저 도착해요.",
        explanation: "대정맥 → 우심방 순서입니다. 우심방은 산소가 적은 혈액을 받아 우심실로 넘깁니다."
    },
    {
        id: "tricuspid",
        target: "tricuspid",
        shortLabel: "삼첨판",
        location: "우심방과 우심실 사이",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 오른쪽",
        mission: "혈액이 뒤로 흐르지 않도록 한 방향으로 열리는 문을 통과하세요.",
        fact: "판막은 혈액이 거꾸로 흐르는 것을 막는 문입니다. 우심방과 우심실 사이에는 삼첨판이 있습니다.",
        question: "우심방과 우심실 사이의 판막이 제대로 닫히지 않는다면 어떤 일이 생길까요?",
        choices: ["심실이 수축할 때 혈액 일부가 우심방 쪽으로 되돌아갈 수 있다", "혈액이 곧바로 산소로 바뀐다", "폐에서 기체 교환이 더 빨라진다"],
        answer: "심실이 수축할 때 혈액 일부가 우심방 쪽으로 되돌아갈 수 있다",
        hint: "판막은 혈액이 한 방향으로 흐르게 하는 문이에요.",
        explanation: "판막은 심장이 수축할 때 혈액이 지나온 쪽으로 역류하지 않도록 막아 줍니다."
    },
    {
        id: "pulmonary-artery",
        target: "pulmonary-artery",
        shortLabel: "폐동맥",
        location: "우심실과 폐동맥",
        scene: "heart",
        oxygen: "low",
        chapter: "심장 → 폐",
        mission: "우심실의 수축을 타고 산소를 얻으러 폐로 출발하세요.",
        fact: "동맥은 산소량이 아니라 흐르는 방향으로 구분합니다. 심장에서 멀어지는 혈관이 동맥이므로, 폐동맥에는 산소가 적은 혈액이 흐릅니다.",
        question: "폐동맥의 혈액은 산소가 적은데도 ‘동맥’이라고 부르는 까닭은?",
        choices: ["심장에서 폐 쪽으로 나가는 혈관이기 때문에", "항상 산소가 많은 혈액만 흐르기 때문에", "폐포 안으로 직접 들어가는 공기 통로이기 때문에"],
        answer: "심장에서 폐 쪽으로 나가는 혈관이기 때문에",
        hint: "동맥과 정맥은 산소량이 아니라 심장을 기준으로 한 흐름 방향으로 구분해요.",
        explanation: "동맥은 심장에서 나가는 혈관입니다. 그래서 산소가 적은 혈액이 흘러도 폐동맥은 동맥입니다."
    },
    {
        id: "alveoli",
        target: "alveoli",
        shortLabel: "폐포",
        location: "폐포를 감싼 모세혈관",
        scene: "lung",
        oxygen: "exchange",
        chapter: "폐순환의 중심",
        mission: "폐포에서 이산화탄소를 내려놓고 산소를 받아오세요.",
        fact: "폐포와 모세혈관의 얇은 벽 사이에서 기체가 이동합니다. 산소는 폐포에서 혈액으로, 이산화탄소는 혈액에서 폐포로 이동합니다.",
        question: "폐포에서 일어나는 기체 교환을 바르게 나타낸 것은?",
        choices: ["산소는 혈액으로, 이산화탄소는 폐포로", "산소와 이산화탄소가 모두 혈액으로", "산소는 폐포로, 이산화탄소는 혈액으로"],
        answer: "산소는 혈액으로, 이산화탄소는 폐포로",
        hint: "우리가 들이마신 산소는 혈액에 실려 온몸으로 가야 해요.",
        explanation: "폐포에서 산소를 얻은 적혈구는 밝은 붉은색을 띠며 다시 심장으로 향합니다."
    },
    {
        id: "pulmonary-vein",
        target: "pulmonary-vein",
        shortLabel: "폐정맥",
        location: "폐정맥과 좌심방",
        scene: "body",
        oxygen: "rich",
        chapter: "폐 → 심장",
        mission: "새로 얻은 산소를 싣고 심장의 왼쪽 위 방으로 돌아가세요.",
        fact: "정맥은 혈액을 심장 쪽으로 운반합니다. 폐정맥에는 폐에서 산소를 얻은 혈액이 흐릅니다.",
        question: "폐정맥에는 산소가 많은 혈액이 흐르는데도 ‘정맥’인 까닭은?",
        choices: ["폐에서 심장으로 돌아오는 혈관이기 때문에", "혈액의 색이 다른 정맥보다 더 어둡기 때문에", "심장에서 폐로 나가는 혈관이기 때문에"],
        answer: "폐에서 심장으로 돌아오는 혈관이기 때문에",
        hint: "정맥은 혈액의 산소량이 아니라 심장으로 돌아오는 방향을 뜻해요.",
        explanation: "폐정맥은 산소가 많은 혈액을 운반하지만 흐름이 폐에서 심장 쪽이므로 정맥입니다."
    },
    {
        id: "mitral",
        target: "mitral",
        shortLabel: "이첨판",
        location: "좌심방과 좌심실 사이",
        scene: "heart",
        oxygen: "rich",
        chapter: "심장 왼쪽",
        mission: "좌심실로 내려가는 한 방향 판막을 통과하세요.",
        fact: "좌심방과 좌심실 사이의 판막은 이첨판이며 승모판이라고도 합니다. 이 판막도 혈액의 역류를 막습니다.",
        question: "좌심방과 좌심실 사이에도 판막이 필요한 가장 중요한 까닭은?",
        choices: ["좌심실이 수축할 때 혈액이 좌심방으로 역류하지 않게 하기 위해", "혈액 속 이산화탄소를 산소로 바꾸기 위해", "좌심방의 혈액을 차갑게 만들기 위해"],
        answer: "좌심실이 수축할 때 혈액이 좌심방으로 역류하지 않게 하기 위해",
        hint: "심실이 강하게 수축할 때 열린 문이 어느 쪽을 향해야 하는지 생각해 보세요.",
        explanation: "판막이 닫혀야 좌심실의 강한 수축력이 뒤로 새지 않고 대동맥 쪽으로 전달됩니다."
    },
    {
        id: "left-ventricle",
        target: "left-ventricle",
        shortLabel: "좌심실",
        location: "좌심실",
        scene: "heart",
        oxygen: "rich",
        chapter: "온몸으로 보낼 준비",
        mission: "강한 수축을 타고 온몸으로 나갈 준비를 하세요.",
        fact: "좌심실은 혈액을 온몸까지 밀어내야 하므로 네 개의 심장 방 가운데 근육벽이 가장 두껍습니다.",
        question: "좌심실의 근육벽이 우심실보다 더 두꺼운 까닭으로 가장 알맞은 것은?",
        choices: ["혈액을 온몸의 먼 곳까지 보낼 큰 힘이 필요하기 때문에", "폐포에서 직접 산소를 만들기 때문에", "혈액이 좌심실에서 가장 오래 머물기 때문에"],
        answer: "혈액을 온몸의 먼 곳까지 보낼 큰 힘이 필요하기 때문에",
        hint: "우심실은 가까운 폐로, 좌심실은 온몸으로 혈액을 보내요.",
        explanation: "좌심실은 온몸의 혈관으로 혈액을 밀어내야 하므로 더 강한 수축을 만드는 두꺼운 근육벽을 가집니다."
    },
    {
        id: "aorta",
        target: "aorta",
        shortLabel: "대동맥",
        location: "대동맥판과 대동맥",
        scene: "body",
        oxygen: "rich",
        chapter: "심장 → 온몸",
        mission: "심장에서 나가는 가장 큰 동맥을 타고 온몸으로 출발하세요.",
        fact: "좌심실에서 나온 혈액은 대동맥판을 지나 우리 몸에서 가장 큰 동맥인 대동맥으로 들어갑니다.",
        question: "대동맥이 심하게 좁아지면 가장 직접적으로 생길 수 있는 변화는?",
        choices: ["온몸으로 나가는 혈액의 양이 줄어들 수 있다", "폐포로 들어오는 공기의 양만 늘어난다", "대정맥이 음식물을 운반하게 된다"],
        answer: "온몸으로 나가는 혈액의 양이 줄어들 수 있다",
        hint: "대동맥은 좌심실에서 나온 혈액이 온몸으로 향하는 큰 출구예요.",
        explanation: "대동맥이 좁아지면 좌심실에서 온몸으로 혈액을 내보내는 흐름이 방해받습니다."
    },
    {
        id: "tissue-exchange",
        target: "tissue-exchange",
        shortLabel: "모세혈관",
        location: "온몸 조직의 모세혈관",
        scene: "body",
        oxygen: "rich",
        chapter: "온몸순환 완성",
        mission: "마지막으로 조직세포에 산소를 전달해 한 바퀴를 완성하세요.",
        fact: "동맥은 더 작은 세동맥으로 갈라지고 모세혈관에 이어집니다. 얇은 모세혈관 벽을 사이에 두고 산소와 영양소가 조직으로 전달됩니다.",
        question: "혈액과 조직세포 사이에서 산소·영양소·노폐물이 실제로 교환되는 혈관은?",
        choices: ["모세혈관", "대동맥", "대정맥"],
        answer: "모세혈관",
        hint: "벽이 매우 얇고 온몸 구석구석에 퍼져 있는 가장 가는 혈관이에요.",
        explanation: "모세혈관에서 산소를 전달한 혈액은 다시 정맥 쪽으로 모여 순환을 반복합니다."
    }
];

window.BODY_EXPLORER_STAGES = window.CIRCULATION_STAGES;
