window.BODY_EXPLORER_CONFIG = {
    gameId: "nervous",
    messagePrefix: "NERVOUS",
    bestScoreKey: "nervousBestScore",
    namedGreeting: "{name} 신호 탐험가, 감각기관에서 몸의 반응까지 이어지는 신경의 길을 떠나 볼까요?",
    guestGreeting: "신호 탐험대와 함께 감각기관에서 뇌와 척수, 근육까지 이어지는 신경의 길을 살펴보세요.",
    resetAnnouncement: "새 신경 탐험을 기다립니다.",
    stateLabels: {
        sensing: "자극을 느끼는 중",
        incoming: "정보 전달 중",
        processing: "판단 중",
        outgoing: "명령 전달 중",
        reacting: "몸이 반응하는 중"
    },
    resultMessages: {
        perfect: "자극을 느끼고 반응하기까지의 신경 경로를 한 번에 찾아냈어요!",
        great: "훌륭해요. 감각 신경과 운동 신경의 방향만 다시 보면 완벽해요.",
        good: "신경 신호의 여행을 완주했어요. 오답노트로 경로를 다시 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 감각기관에서 시작해 근육에서 끝나는 길을 다시 걸어 봐요."
    }
};

window.BODY_EXPLORER_STAGES = [
    {
        id: "sense-stimulus",
        shortLabel: "감각기관",
        location: "손끝의 피부",
        scene: "sense",
        oxygen: "sensing",
        chapter: "자극 발견",
        mission: "따뜻한 물체에 닿은 손끝에서 첫 신호를 찾아보세요.",
        fact: "눈, 귀, 코, 혀, 피부 같은 감각기관은 빛, 소리, 냄새, 맛, 온도와 접촉 같은 자극을 받아들입니다.",
        question: "따뜻함이나 차가움을 느끼는 감각기관은 무엇일까요?",
        choices: ["피부", "뼈", "혈관"],
        answer: "피부",
        hint: "손으로 얼음이나 따뜻한 컵을 만졌을 때 어느 부분이 먼저 느끼는지 생각해 보세요.",
        explanation: "피부에는 온도와 접촉 같은 자극을 받아들이는 감각 기능이 있습니다."
    },
    {
        id: "make-sensory-information",
        shortLabel: "감각 정보",
        location: "피부와 신경의 시작점",
        scene: "sense",
        oxygen: "sensing",
        chapter: "자극을 정보로",
        mission: "피부가 알아챈 따뜻함을 신경이 전할 수 있는 정보로 바꾸세요.",
        fact: "감각기관이 자극을 받아들이면 신경을 통해 전달할 정보가 만들어집니다.",
        question: "감각기관이 자극을 받아들인 다음 하는 일은 무엇일까요?",
        choices: ["신경에 정보를 보낸다", "피를 만든다", "음식을 소화한다"],
        answer: "신경에 정보를 보낸다",
        hint: "뇌가 자극을 알 수 있도록 이어 주는 길을 생각해 보세요.",
        explanation: "감각기관에서 생긴 정보는 신경을 따라 뇌와 척수 쪽으로 전달됩니다."
    },
    {
        id: "sensory-nerve",
        shortLabel: "감각 신경",
        location: "팔의 감각 신경",
        scene: "sensory-nerve",
        oxygen: "incoming",
        chapter: "정보가 들어가는 길",
        mission: "손끝에서 온 정보를 뇌와 척수 쪽으로 운반하세요.",
        fact: "감각 신경은 감각기관이 받아들인 정보를 뇌와 척수 쪽으로 전달합니다.",
        question: "손끝의 감각 정보를 뇌와 척수 쪽으로 보내는 신경은?",
        choices: ["감각 신경", "운동 신경", "근육"],
        answer: "감각 신경",
        hint: "이름에 ‘감각’이 들어 있는 신경을 찾아보세요.",
        explanation: "감각 신경은 몸에서 받아들인 정보를 안쪽의 뇌와 척수로 전달합니다."
    },
    {
        id: "spinal-cord-incoming",
        shortLabel: "척수",
        location: "등뼈 안쪽의 척수",
        scene: "spinal",
        oxygen: "incoming",
        chapter: "몸과 뇌를 잇는 길",
        mission: "몸에서 온 정보를 척수를 지나 뇌 쪽으로 이어 주세요.",
        fact: "척수는 등뼈 안쪽을 지나며 뇌와 몸 사이에서 신경 신호가 오가는 중요한 길입니다.",
        question: "뇌와 몸 사이에서 신경 신호가 오가는 중요한 길은 무엇일까요?",
        choices: ["척수", "위", "폐"],
        answer: "척수",
        hint: "등뼈 안쪽을 길게 지나가는 기관입니다.",
        explanation: "척수는 뇌와 이어져 몸의 여러 신경 신호가 오가도록 돕습니다."
    },
    {
        id: "brain-receives",
        shortLabel: "뇌",
        location: "뇌의 정보실",
        scene: "brain",
        oxygen: "processing",
        chapter: "정보 도착",
        mission: "손끝에서 출발한 감각 정보를 뇌에 전달하세요.",
        fact: "뇌는 감각기관에서 전달된 정보를 받아 무엇을 느꼈는지 알아봅니다.",
        question: "도착한 감각 정보를 받아들이고 알아보는 기관은?",
        choices: ["뇌", "심장", "콩팥"],
        answer: "뇌",
        hint: "생각하고 판단하는 일을 맡은 기관입니다.",
        explanation: "뇌는 들어온 감각 정보를 받아 상황을 알아보고 판단합니다."
    },
    {
        id: "brain-decides",
        shortLabel: "판단",
        location: "뇌의 판단실",
        scene: "brain",
        oxygen: "processing",
        chapter: "어떻게 반응할까?",
        mission: "따뜻한 물체에서 손을 옮기도록 알맞은 반응을 정하세요.",
        fact: "뇌는 들어온 정보를 바탕으로 몸이 어떻게 반응할지 정하고 명령을 보냅니다.",
        question: "뇌가 감각 정보를 받은 뒤 하는 일로 알맞은 것은?",
        choices: ["알맞은 반응을 판단한다", "산소를 만든다", "음식을 잘게 부순다"],
        answer: "알맞은 반응을 판단한다",
        hint: "느낀 뒤에는 무엇을 할지 정해야 합니다.",
        explanation: "뇌는 상황을 판단하고 몸의 알맞은 부분에 움직임 명령을 보냅니다."
    },
    {
        id: "command-through-spinal-cord",
        shortLabel: "운동 명령",
        location: "뇌에서 척수로",
        scene: "spinal",
        oxygen: "outgoing",
        chapter: "명령이 나가는 길",
        mission: "손을 움직이라는 명령을 뇌에서 몸 쪽으로 내려보내세요.",
        fact: "뇌에서 나온 움직임 명령도 척수를 거쳐 몸의 운동 신경 쪽으로 전달됩니다.",
        question: "뇌의 움직임 명령은 몸으로 가기 위해 주로 어느 기관을 거칠까요?",
        choices: ["척수", "식도", "기관지"],
        answer: "척수",
        hint: "뇌와 몸을 이어 주는 신경 신호의 큰길입니다.",
        explanation: "뇌의 명령은 척수를 거쳐 몸의 운동 신경으로 이어집니다."
    },
    {
        id: "motor-nerve",
        shortLabel: "운동 신경",
        location: "팔의 운동 신경",
        scene: "motor",
        oxygen: "outgoing",
        chapter: "근육으로 가는 길",
        mission: "척수에서 나온 움직임 명령을 팔 근육까지 운반하세요.",
        fact: "운동 신경은 뇌와 척수에서 나온 명령을 근육으로 전달합니다.",
        question: "움직임 명령을 근육으로 전달하는 신경은?",
        choices: ["운동 신경", "감각 신경", "감각기관"],
        answer: "운동 신경",
        hint: "몸을 ‘운동’하게 만드는 명령을 나르는 신경입니다.",
        explanation: "운동 신경이 명령을 근육에 전달하면 몸을 움직일 수 있습니다."
    },
    {
        id: "muscle-reacts",
        shortLabel: "근육",
        location: "팔과 손의 근육",
        scene: "reaction",
        oxygen: "reacting",
        chapter: "몸의 반응",
        mission: "명령을 받은 근육을 움직여 손을 안전한 곳으로 옮기세요.",
        fact: "명령을 받은 근육이 오므라들거나 풀리면서 팔과 손이 움직입니다.",
        question: "운동 신경의 명령을 받아 실제로 팔을 움직이는 것은?",
        choices: ["근육", "피부의 땀", "혈액"],
        answer: "근육",
        hint: "뼈를 당겨 몸을 움직이게 하는 부분입니다.",
        explanation: "근육이 움직이면서 손이 따뜻한 물체에서 떨어지는 반응이 나타납니다."
    },
    {
        id: "complete-path",
        shortLabel: "반응 완성",
        location: "감각에서 반응까지",
        scene: "reaction",
        oxygen: "reacting",
        chapter: "신경 탐험 완주",
        mission: "자극을 느끼고 몸이 반응하는 전체 길을 순서대로 연결하세요.",
        fact: "감각기관이 자극을 받아들이고, 신경이 정보를 전달하며, 뇌와 척수가 판단과 명령을 이어 몸이 반응합니다.",
        question: "자극을 느끼고 몸이 반응하는 순서로 알맞은 것은?",
        choices: ["감각기관 → 감각 신경 → 뇌·척수 → 운동 신경 → 근육", "근육 → 뇌 → 감각기관 → 척수", "심장 → 폐 → 위 → 근육"],
        answer: "감각기관 → 감각 신경 → 뇌·척수 → 운동 신경 → 근육",
        hint: "느끼는 곳에서 시작해 실제로 움직이는 곳에서 끝납니다.",
        explanation: "자극은 감각기관에서 받아들이고 감각 신경을 따라 뇌와 척수에 전달됩니다. 명령은 운동 신경을 따라 근육에 도착해 반응을 만듭니다."
    }
];
