window.BODY_EXPLORER_CONFIG = {
    gameId: "respiration",
    messagePrefix: "RESPIRATION",
    bestScoreKey: "respirationBestScore",
    namedGreeting: "{name} 탐험가, 산소 방울과 함께 호흡 여행을 떠나 볼까요?",
    guestGreeting: "산소 방울이 되어 코에서 폐와 온몸까지 호흡의 길을 여행해 보세요.",
    resetAnnouncement: "새 호흡 탐험을 기다립니다.",
    stateLabels: {
        entering: "들이마시는 중",
        moving: "공기 길 이동 중",
        exchanging: "기체 교환 중",
        delivering: "산소 전달 중",
        returning: "이산화탄소 회수 중",
        exhaling: "내쉬는 중"
    },
    resultMessages: {
        perfect: "호흡의 길과 기체의 이동 방향을 모두 한 번에 찾았어요!",
        great: "훌륭해요. 헷갈린 기체의 방향만 다시 보면 완벽해요.",
        good: "호흡 여행을 완주했어요. 오답노트로 순서를 이어 보세요.",
        retry: "끝까지 완주한 것이 중요해요. 공기의 길을 읽고 다시 도전해 봐요."
    }
};

window.BODY_EXPLORER_STAGES = [
    {
        id: "air-enters-nose",
        shortLabel: "코",
        location: "코",
        scene: "nose",
        oxygen: "entering",
        chapter: "공기의 입구",
        mission: "바깥 공기와 함께 몸속으로 들어가세요.",
        fact: "숨을 들이마시면 공기가 코나 입으로 들어옵니다. 코는 공기 속의 큰 먼지를 걸러 주는 데 도움을 줍니다.",
        question: "공기가 몸속으로 처음 들어오는 곳으로 알맞은 것은?",
        choices: ["코나 입", "위나 작은창자", "심장이나 혈관"],
        answer: "코나 입",
        hint: "숨을 들이마실 때 공기가 드나드는 얼굴의 부분을 생각해 보세요.",
        explanation: "들이마신 공기는 코나 입을 지나 몸속의 공기 길로 들어갑니다."
    },
    {
        id: "inhale-lungs-expand",
        shortLabel: "들이마심",
        location: "가슴과 폐",
        scene: "lungs",
        oxygen: "entering",
        chapter: "들이마시는 숨",
        mission: "가슴이 넓어지는 움직임을 타고 폐로 들어가세요.",
        fact: "숨을 들이마시면 가슴 안의 공간이 넓어지고 폐가 부풀면서 공기가 들어옵니다.",
        question: "숨을 들이마실 때 나타나는 변화는?",
        choices: ["가슴이 넓어지고 공기가 들어온다", "폐가 작아지고 공기가 나간다", "위가 움직여 공기를 보낸다"],
        answer: "가슴이 넓어지고 공기가 들어온다",
        hint: "두 손을 가슴에 대고 크게 숨을 들이마셔 보세요.",
        explanation: "들이마실 때 가슴 안 공간이 넓어지면서 폐가 부풀고 공기가 들어옵니다."
    },
    {
        id: "trachea",
        shortLabel: "기관",
        location: "기관",
        scene: "airway",
        oxygen: "moving",
        chapter: "폐로 가는 공기 길",
        mission: "목에서 가슴으로 이어지는 굵은 공기 길을 따라가세요.",
        fact: "기관은 목에서 가슴까지 이어져 공기가 폐로 드나들게 하는 관입니다.",
        question: "코나 입으로 들어온 공기가 폐로 갈 때 지나는 굵은 관은?",
        choices: ["기관", "식도", "대정맥"],
        answer: "기관",
        hint: "음식이 지나는 식도와 달리 공기가 지나는 관이에요.",
        explanation: "코나 입으로 들어온 공기는 기관을 따라 폐 쪽으로 이동합니다."
    },
    {
        id: "bronchi",
        shortLabel: "기관지",
        location: "기관지",
        scene: "airway",
        oxygen: "moving",
        chapter: "두 폐로 갈라지는 길",
        mission: "기관 끝에서 갈라지는 두 길 중 폐로 이어지는 길을 따라가세요.",
        fact: "기관은 가슴에서 두 갈래의 기관지로 나뉘고, 기관지는 오른쪽과 왼쪽 폐로 이어집니다.",
        question: "기관 끝에서 두 폐로 갈라지는 공기 길은?",
        choices: ["기관지", "혈관", "큰창자"],
        answer: "기관지",
        hint: "기관의 끝에서 나뭇가지처럼 갈라지는 길이에요.",
        explanation: "기관 → 기관지 → 폐 속의 더 가는 공기 길 순서로 공기가 이동합니다."
    },
    {
        id: "alveoli-arrival",
        shortLabel: "폐포",
        location: "폐 속의 폐포",
        scene: "alveoli",
        oxygen: "exchanging",
        chapter: "작은 공기주머니",
        mission: "기관지 끝의 포도송이 같은 작은 공기주머니에 도착하세요.",
        fact: "기관지의 가는 끝에는 포도송이처럼 생긴 아주 작은 공기주머니인 폐포가 많이 있습니다.",
        question: "폐에서 산소와 이산화탄소가 오가는 작은 공기주머니는?",
        choices: ["폐포", "심실", "방광"],
        answer: "폐포",
        hint: "폐 속에 아주 많이 모여 있고 포도송이처럼 보여요.",
        explanation: "폐포는 주변의 가는 혈관과 맞닿아 있어 기체가 오가기 좋습니다."
    },
    {
        id: "oxygen-to-blood",
        shortLabel: "산소 이동",
        location: "폐포와 혈액 사이",
        scene: "exchange",
        oxygen: "exchanging",
        chapter: "기체 교환",
        mission: "들이마신 공기의 산소를 폐포에서 혈액으로 보내세요.",
        fact: "폐포의 산소는 얇은 벽을 지나 주변의 혈액으로 이동합니다.",
        question: "폐포에 도착한 산소는 다음에 어디로 이동할까?",
        choices: ["주변 혈액", "위 속", "큰창자"],
        answer: "주변 혈액",
        hint: "산소는 혈액을 타야 온몸으로 갈 수 있어요.",
        explanation: "산소는 폐포에서 혈액으로 이동하고, 혈액은 산소를 온몸으로 운반합니다."
    },
    {
        id: "oxygen-to-body",
        shortLabel: "온몸",
        location: "온몸의 세포",
        scene: "body",
        oxygen: "delivering",
        chapter: "산소 전달",
        mission: "혈액을 타고 온몸의 세포에 산소를 전달하세요.",
        fact: "혈액은 폐에서 얻은 산소를 온몸의 세포로 운반합니다. 세포는 활동하는 데 산소가 필요합니다.",
        question: "혈액이 폐에서 얻은 산소를 가져다주는 곳은?",
        choices: ["온몸의 세포", "몸 밖의 공기", "음식물 속"],
        answer: "온몸의 세포",
        hint: "우리 몸의 모든 부분이 움직이고 활동하려면 산소가 필요해요.",
        explanation: "산소는 혈액을 따라 온몸으로 이동해 세포가 활동하는 데 쓰입니다."
    },
    {
        id: "carbon-dioxide-return",
        shortLabel: "이산화탄소",
        location: "세포에서 폐로 돌아가는 길",
        scene: "body",
        oxygen: "returning",
        chapter: "이산화탄소 회수",
        mission: "세포에서 생긴 이산화탄소를 싣고 폐로 돌아가세요.",
        fact: "세포가 활동하면 이산화탄소가 생깁니다. 혈액은 이산화탄소를 받아 폐로 운반합니다.",
        question: "세포에서 생긴 이산화탄소를 폐까지 운반하는 것은?",
        choices: ["혈액", "뼈", "침"],
        answer: "혈액",
        hint: "산소를 운반했던 것과 같은 몸속의 흐르는 길을 이용해요.",
        explanation: "혈액은 산소를 세포에 주고, 세포에서 생긴 이산화탄소를 받아 폐로 돌아갑니다."
    },
    {
        id: "carbon-dioxide-to-alveoli",
        shortLabel: "폐로 회수",
        location: "폐포와 혈액 사이",
        scene: "exchange",
        oxygen: "returning",
        chapter: "기체 교환",
        mission: "혈액 속 이산화탄소를 폐포 안으로 옮기세요.",
        fact: "폐에서는 산소가 혈액으로 이동하는 동시에 이산화탄소가 혈액에서 폐포로 이동합니다.",
        question: "폐에 도착한 이산화탄소가 이동하는 방향은?",
        choices: ["혈액에서 폐포로", "폐포에서 혈액으로", "코에서 온몸의 세포로"],
        answer: "혈액에서 폐포로",
        hint: "이산화탄소는 다음에 내쉬는 숨과 함께 몸 밖으로 나가야 해요.",
        explanation: "폐포로 이동한 이산화탄소는 내쉬는 공기에 섞여 몸 밖으로 나갑니다."
    },
    {
        id: "exhale-out",
        shortLabel: "내쉬기",
        location: "폐에서 몸 밖으로",
        scene: "lungs",
        oxygen: "exhaling",
        chapter: "호흡 여행 완성",
        mission: "이산화탄소가 든 공기를 기관을 거쳐 몸 밖으로 내보내세요.",
        fact: "숨을 내쉬면 가슴 안 공간이 작아지고 폐가 줄어들면서 공기가 기관을 거쳐 코나 입으로 나갑니다.",
        question: "숨을 내쉴 때 이산화탄소가 든 공기가 나가는 길은?",
        choices: ["폐 → 기관지 → 기관 → 코나 입", "폐 → 식도 → 위", "폐 → 작은창자 → 입"],
        answer: "폐 → 기관지 → 기관 → 코나 입",
        hint: "들이마신 공기가 들어왔던 길을 반대로 돌아가요.",
        explanation: "들이마심과 내쉼이 반복되면서 산소를 얻고 이산화탄소를 몸 밖으로 내보냅니다."
    }
];
